# numpy

In [5]:
import numpy as np

In [13]:
a=np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [14]:
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [15]:
print(np.mean(a))
print(np.mean(a,axis=1))

4.5
[2.5 6.5]


In [16]:
a+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# tensorflow

In [1]:
import tensorflow as tf

In [2]:
with tf.name_scope('abc'):
    a=tf.constant(3,dtype=tf.float32,name='const')
print(a)

with tf.Session() as sess:
    print(sess.run(a))

Tensor("abc/const:0", shape=(), dtype=float32)
3.0


In [14]:
a=tf.constant(3,dtype=tf.float32,name='const')
b=tf.Variable(0,dtype=tf.float32)
c=tf.assign(b,a+b)
print(a)
print(b)

init=tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))
    print(sess.run(c))

Tensor("const_1:0", shape=(), dtype=float32)
<tf.Variable 'Variable_2:0' shape=() dtype=float32_ref>
3.0
6.0


In [6]:
np.random.seed(42)
x=tf.placeholder(tf.float32,shape=(),name='x')
y=tf.placeholder(tf.float32,shape=(),name='y')
w=tf.Variable(np.random.randn(),dtype=tf.float32)

a=tf.assign(w,w + x + y)

init=tf.global_variables_initializer()

with tf.Session() as sess :
    sess.run(init)
    for _ in range(0,10) :
        print(sess.run(w))
        sess.run(a,feed_dict={x:1.0,y:2.0})
    print(sess.run(w))

0.49671414
3.496714
6.496714
9.496714
12.496714
15.496714
18.496714
21.496714
24.496714
27.496714
30.496714
